### ISSUE TITLE
TypeError: stateMachineProvider.setConfig is not a function

### ISSUE THREAD

**Issue by ppaulogustavo** [tafax/angular-state-machine#8]
Hi, I'm trying to use your code to make a configuration state machine, but doesn't work.. 

When I call the method "setConfig" from stateMachineProvider, is it make this error:

Uncaught Error: [$injector:modulerr] Failed to instantiate module BssJS due to:
TypeError: stateMachineProvider.setConfig is not a function
    at file:///C:/Desenvolvimento/workspace/BSSJs/scripts/app.js:4:24
    at Object.invoke (file:///C:/Desenvolvimento/workspace/BSSJs/libs/angular.js:4478:17)
    at runInvokeQueue (file:///C:/Desenvolvimento/workspace/BSSJs/libs/angular.js:4384:35)
    at file:///C:/Desenvolvimento/workspace/BSSJs/libs/angular.js:4393:11
    at forEach (file:///C:/Desenvolvimento/workspace/BSSJs/libs/angular.js:336:20)
    at loadModules (file:///C:/Desenvolvimento/workspace/BSSJs/libs/angular.js:4374:5)
    at createInjector (file:///C:/Desenvolvimento/workspace/BSSJs/libs/angular.js:4299:11)
    at doBootstrap (file:///C:/Desenvolvimento/workspace/BSSJs/libs/angular.js:1657:20)
    at bootstrap (file:///C:/Desenvolvimento/workspace/BSSJs/libs/angular.js:1678:12)
    at angularInit (file:///C:/Desenvolvimento/workspace/BSSJs/libs/angular.js:1572:5)
http://errors.angularjs.org/1.4.7/$injector/modulerr?p0=BssJS&p1=TypeError%…FC%3A%2FDesenvolvimento%2Fworkspace%2FBSSJs%2Flibs%2Fangular.js%3A1572%3A5)

Using his example the same error occurs.. 

Here is my code:

angular.module('BssJS', ['FSM']);
angular.module('BssJS').config(function(stateMachineProvider){
    console.log(stateMachineProvider);
    stateMachineProvider.setConfig({});
});

In javascript console, the object stateMachineProvider do not have the setConfig method. Can you help-me ? 

Sorry for my english, I'm not good :(

**Comment by tafax** [comment]
Hi @ppaulogustavo,
actually the method is `config` and not `setConfig`, sorry for that I misremembered to update the README.
